#!/bin/bash

source /opt/k8comp/k8comp.conf

programname=$0

usage() {
  echo -e "\n\x1b[32m Usage: $programname [-h | -p <project_name> -a <application> -e <environment> ] \x1b[0m"
  echo -e "\x1b[32m  -h | --help :                           Display usage information. \x1b[0m"
  echo -e "\x1b[32m  -p | --project <project_name> :         Project name as specified on the projects folder. Configuration specified in k8comp.conf. Current path ${projects_path} \x1b[0m"
  echo -e "\x1b[32m  -a | --application <application> :      The name of the application which need to be deployed. ${projects_path}/<project>/<application>/<application>.yaml \x1b[0m"
  echo -e "\x1b[32m  -e | --environment <environment> :      The environment will be checked from hiera. If no values are found in hiera the variables will not be replaced. \x1b[0m"
  echo -e "\x1b[32m  -x | --xtra <variable> :                The variable specified on the cmd run it will be used to update a value on the final yaml file. This will have priority over hiera value. Is not mandatory to be specified. The format is variable=value \x1b[0m"
  echo -e "\n\x1b[32m Example:

  k8comp -p project1 -a app1 -e development | kubectl create -f -
  k8comp -p project1 -a app1 -e development | kubectl apply -f -

  k8comp -p project1 -a app1 -e development -x var1=value1 -x var2=value2 | kubectl create -f -
  k8comp -p project1 -a app1 -e development -x var1=value1 -x var2=value2 | kubectl apply -f -

  Dry run:

  k8comp -p project1 -a app1 -e development
  k8comp -p project1 -a app1 -e development -x var1=value1\x1b[0m\n"
}

read_x_args()
{
    while (($#)) && [[ $1 != -* ]]; do args+=("$1"); shift; done
}

while [ $# -gt 0 ]; do
  case "$1" in
    -p|--project)
      if [ -n "$2" ]; then
        project=$2
        shift
      else
        usage
        exit 1
      fi
    ;;
    -a|--application)
      if [ -n "$2" ]; then
        application=$2
        shift
      else
        usage
        exit 1
      fi
    ;;
    -e|--environment)
      if [ -n "$2" ]; then
        environment=$2
        shift
      else
        usage
        exit 1
      fi
    ;;
    -x|--xtra)
      read_x_args "${@:2}"
    ;;
    -h|--help)
      usage
      exit 0
    ;;
  esac
  shift
done

# Define the location of the locations
deployments=${k8comp_home}/deployments/${project}/${application}-${environment}/${application}-`date +%Y-%m-%d-%H-%M-%S`

# Location of the most current deployment/test
latest_deployment=${k8comp_home}/deployments/${project}/${application}-${environment}/latest

# check if the required values are declared
if [ -z ${environment} ] || [ -z ${application} ] || [ -z ${project} ]
	then
	usage
	exit 1
fi

# check if the default yaml file is available
if [ ! -f ${projects_path}/${project}/${application}/${application}.yaml ]
 then
  echo -e "\n\033[31m[ERROR]   Main application YAML file not found in ${projects_path}\033[0m\n"
  exit 1
fi


mkdir -p ${deployments}
ln -sfn ${deployments} ${latest_deployment}
rsync -av ${projects_path}/${project}/${application}/${application}.yaml ${deployments} > /dev/null

sed -i "s|%{project}|${project}|g" ${deployments}/${application}.yaml
sed -i "s|%{application}|${application}|g" ${deployments}/${application}.yaml
sed -i "s|%{environment}|${environment}|g" ${deployments}/${application}.yaml

# replace the variables declared on the cmd
for xvariable in ${args[@]}
do
  variable=$(echo ${xvariable} | { IFS='=' read -a array; echo ${array[0]}; })
  value=$(echo ${xvariable} | { IFS='=' read -a array; echo ${array[1]}; })
  sed -i "s|%{${variable}}|${value}|g" ${deployments}/${application}.yaml
done

# find and replace the rest of the variables with hiera values
for variable in `grep -o '\%{[a-z,A-Z,0-9,_,-]*\}' ${projects_path}/${project}/${application}/${application}.yaml | sort | uniq | sed 's|[%{}]||g'`
do
if [ -z `hiera -c ${custom_hiera} ${variable} project=${project} application=${application} environment=${environment}` ];
   then
   echo -e "\n\033[31m${variable} not found in hiera\033[0m\n"
  exit 1
  else
   sed -i "s|%{${variable}}|`hiera -c ${custom_hiera} ${variable} project=${project} application=${application} environment=${environment}`|g" ${deployments}/${application}.yaml
  fi
done

cat ${deployments}/${application}.yaml

ls -td --group-directories-first ${k8comp_home}/deployments/${project}/${application}-${environment}/${application}-* | tail -n +${deployments_history} | xargs -I % rm -rf %
